default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: db

development:
  <<: *default
  database: to_do_development

test:
  <<: *default
  database: to_do_test

production:
  <<: *default
  database: to_do_production
